# Compatibility shim — do NOT delete until all callers are updated.
# Import everything from the new place subpackage so that
#   from localsignal_engine.place_knowledge import X
# continues to work unchanged.
from localsignal_engine.place import *  # noqa: F401, F403
from localsignal_engine.place import (
    ensure_place_knowledge_schema,
    DOCUMENT_MIN_CHARS,
    EMBEDDING_MODEL,
    RESTAURANT_BRIEF_SOURCE,
    BRIEF_STALENESS_DAYS,
    upsert_place_document,
    sync_existing_evidence_documents,
    embed_place_documents,
    retrieve_place_documents,
    ingest_google_place_documents,
    ingest_website_documents,
    build_restaurant_brief_documents,
    build_place_profiles_from_briefs,
    extract_place_food_facts_from_brief,
    get_place_food_facts,
    place_profile,
    upsert_place_profile,
    merge_place_profile,
    _embed_texts,
    _vector_literal,
    _document_prompt_row,
    _dedupe_document_rows,
    _text_hash,
    _clean_text,
    _google_place_details,
    _google_profile_content,
    _fetch_json,
    _website_candidate_urls,
    _website_content_type,
    _fetch_webpage,
    _TextExtractor,
    _review_time,
    _maps_url,
    _string_list,
    _clean_json_value,
    _dedupe_display_values,
    _places,
    _upsert_profile_from_brief,
    _brief_is_fresh,
    _restaurant_brief_context,
    _generate_restaurant_brief,
    _repair_restaurant_brief,
    _parse_llm_json,
    _restaurant_brief_content,
    _brief_doc,
    _brief_location_format,
)
